-- Trigger para função de atualizar limite de credito do cliente

CREATE TRIGGER TRG_ATUALIZAR_LIMITE_CREDITO
AFTER INSERT OR UPDATE ON FATURA
FOR EACH ROW
EXECUTE FUNCTION ATUALIZAR_LIMITE_CREDITO();