-- Criação da tabela CLIENTE

CREATE TABLE IF NOT EXISTS CLIENTE (
	ID_CLIENTE SERIAL PRIMARY KEY,
	NOME VARCHAR ( 50 ) NOT NULL,
	IDADE INTEGER NOT NULL,
	STATUS_BLOQUEIO CHAR(1) NOT NULL DEFAULT 'A',
	LIMITE_CREDITO DECIMAL(10, 2) NOT NULL
);