-- Criação da tabela CLIENTE

CREATE TABLE IF NOT EXISTS FATURA (
	ID_FATURA SERIAL PRIMARY KEY,
	DATA_VENCIMENTO DATE NOT NULL,
	VALOR DECIMAL(10, 2) NOT NULL,
	STATUS CHAR(1) NOT NULL,
	ID_CLIENTE INTEGER REFERENCES CLIENTE(ID_CLIENTE)
);