-- Criação da tabela de clientes

CREATE TABLE IF NOT EXISTS PAGAMENTO (
	ID_PAGAMENTO SERIAL PRIMARY KEY,
	DATA_PAGAMENTO DATE,
	VALOR DECIMAL(10, 2),
	ID_FATURA INTEGER REFERENCES FATURA(ID_FATURA)
);