-- View para verificar clientes que realizaram pagamento no dia anterior ao vencimento da Fatura.

CREATE OR REPLACE VIEW V_PAGAMENTOS_DIA_ANTERIOR AS
	SELECT
		C.ID_CLIENTE,
		F.VALOR,
		P.DATA_PAGAMENTO
	FROM
		CLIENTE   C
		JOIN FATURA F
		ON C.ID_CLIENTE = F.ID_CLIENTE JOIN PAGAMENTO P
		ON F.ID_FATURA = P.ID_FATURA
	WHERE
		P.DATA_PAGAMENTO = F.DATA_VENCIMENTO - INTERVAL '1 DAY';