-- View para verificar clientes que realizaram pagamento no dia do vencimento da Fatura.

CREATE OR REPLACE VIEW V_PAGAMENTOS_DIA_VENCIMENTO AS
	SELECT
		F.DATA_VENCIMENTO,
		COUNT(*) AS QUANTIDADE
	FROM
		FATURA    F
		JOIN PAGAMENTO P
		ON F.ID_FATURA = P.ID_FATURA
	WHERE
		F.DATA_VENCIMENTO = P.DATA_PAGAMENTO
	GROUP BY
		F.DATA_VENCIMENTO;